src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
src/main/java/com/favoriteplace/app/converter/RallyConverter.java
src/main/java/com/favoriteplace/app/repository/LikedRallyRepository.java
src/main/java/com/favoriteplace/app/repository/PilgrimageRepository.java
src/main/java/com/favoriteplace/app/repository/RallyRepository.java
src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java

- 이달의 추천 랠리 api 개발
- 지역 상세 조회 리스트 api 개발

[FEAT] 성지순례 조회 API 개발 완료

---

src/main/java/com/favoriteplace/app/controller/ShopController.java
src/main/java/com/favoriteplace/app/service/ShopService.java

`TODO`
> 리팩토링 추후 필요할 듯한 부분 있음
> 조회쿼리를 신경썼는데, 더 최적화할 수 있는 부분이 있을 것 같다..

[FEAT #28] 상점 - 상시판매 API 구현 

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/MyPageController.java
src/main/java/com/favoriteplace/app/converter/MyPageConverter.java
src/main/java/com/favoriteplace/app/dto/MyPageDto.java
src/main/java/com/favoriteplace/app/repository/AcquiredItemRepository.java
src/main/java/com/favoriteplace/app/repository/BlockRepository.java
src/main/java/com/favoriteplace/app/repository/ItemRepository.java
src/main/java/com/favoriteplace/app/service/MyPageQueryService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java

> 내정보 조회 api는 기획 답변을 못 들어서 보류했습니다. 성지순례 post 컨트롤러 작업은 팀원분들 코드에 형식을 맞추는게 좋을 것 같아서 마이페이지부터 작업했습니다.
- 프로필 조회 api 개발
- 보유 아이템 조회 api 개발
- 차단한 사용자 목록 조회 api 개발

[FEAT] 마이페이지 내 정보 조회 API 개발

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/ShopController.java
src/main/java/com/favoriteplace/app/domain/item/Item.java
src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
src/main/java/com/favoriteplace/app/repository/AcquiredItemRepository.java
src/main/java/com/favoriteplace/app/repository/ItemRepository.java
src/main/java/com/favoriteplace/app/service/ShopService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/util/SecurityUtil.java

`TODO`
> 스케줄링 기능을 통해 NEW 카테고리의 경우 시간이 지나면 NEW 카테고리 말고 다른 카테고리로 이동? 시키는 작업 필요 -> 어느 카테고리로 이동시킽 지 논의 필요

[FEAT #39] - 상점 상세페이지 API 구현

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
src/main/java/com/favoriteplace/app/converter/CommonConverter.java
src/main/java/com/favoriteplace/app/converter/MyPageConverter.java
src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
src/main/java/com/favoriteplace/app/converter/PointHistoryConverter.java
src/main/java/com/favoriteplace/app/domain/Member.java
src/main/java/com/favoriteplace/app/domain/enums/RallyVersion.java
src/main/java/com/favoriteplace/app/domain/item/PointHistory.java
src/main/java/com/favoriteplace/app/domain/travel/CompleteRally.java
src/main/java/com/favoriteplace/app/domain/travel/Rally.java
src/main/java/com/favoriteplace/app/dto/CommonResponseDto.java
src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
src/main/java/com/favoriteplace/app/repository/CommentRepository.java
src/main/java/com/favoriteplace/app/repository/CompleteRallyRepository.java
src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
src/main/java/com/favoriteplace/app/repository/PointHistoryRepository.java
src/main/java/com/favoriteplace/app/repository/PostRepository.java
src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
src/main/java/com/favoriteplace/app/service/MyPageQueryService.java
src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java

- 내정보 조회 api 개발
- 프로필 조회 api 개발 
- 보유 아이템 조회 api 개발
- 차단한 사용자 목록 조회 api 개발

[FEAT] 마이페이지 내 정보 조회 관련 api 개발

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/GuestBookController.java
src/main/java/com/favoriteplace/app/controller/PostController.java
src/main/java/com/favoriteplace/app/controller/TrendingPostController.java
src/main/java/com/favoriteplace/app/converter/CommentConverter.java
src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
src/main/java/com/favoriteplace/app/domain/community/Comment.java
src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
src/main/java/com/favoriteplace/app/domain/community/Post.java
src/main/java/com/favoriteplace/app/dto/community/CommentResponseDto.java
src/main/java/com/favoriteplace/app/dto/community/Empty.java
src/main/java/com/favoriteplace/app/dto/community/GuestBookRequestDto.java
src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java
src/main/java/com/favoriteplace/app/dto/community/PostRequestDto.java
src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
src/main/java/com/favoriteplace/app/dto/community/TrendingPostResponseDto.java
src/main/java/com/favoriteplace/app/repository/HashtagRepository.java
src/main/java/com/favoriteplace/app/repository/ImageRepository.java
src/main/java/com/favoriteplace/app/repository/LikedPostRepository.java
src/main/java/com/favoriteplace/app/service/CommentService.java
src/main/java/com/favoriteplace/app/service/GuestBookCommandService.java
src/main/java/com/favoriteplace/app/service/GuestBookQueryService.java
src/main/java/com/favoriteplace/app/service/LikedPostService.java
src/main/java/com/favoriteplace/app/service/PostCommandService.java
src/main/java/com/favoriteplace/app/service/PostQueryService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
src/main/java/com/favoriteplace/global/util/SecurityUtil.java

커뮤니티 - 자유게시판 : get api response 수정
커뮤니티 - 자유게시판 : 게시글 CUD 수정

[FEAT #36] 커뮤니티 - 자유게시판 api 수정

---

build.gradle
src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
src/main/java/com/favoriteplace/app/controller/GuestBookController.java
src/main/java/com/favoriteplace/app/controller/PostCommentController.java
src/main/java/com/favoriteplace/app/controller/PostController.java
src/main/java/com/favoriteplace/app/controller/TrendingPostController.java
src/main/java/com/favoriteplace/app/domain/community/Comment.java
src/main/java/com/favoriteplace/app/service/Empty.java
src/main/java/com/favoriteplace/app/service/community/CommentCommandService.java
src/main/java/com/favoriteplace/app/service/community/CommentQueryService.java
src/main/java/com/favoriteplace/app/service/community/CountCommentsService.java
src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
src/main/java/com/favoriteplace/app/service/community/LikedPostService.java
src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
src/main/java/com/favoriteplace/app/service/community/PostQueryService.java
src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLatestStrategy.java
src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLikedStrategy.java
src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLatestStrategy.java
src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLikedStrategy.java
src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortStrategy.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/gcpImage/GoogleCloudStorageConfig.java
src/main/java/com/favoriteplace/global/gcpImage/UploadImage.java
src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java

완료한 api
- 댓글 수정 (자유게시판)
- 댓글 삭제 (자유게시판)
- 댓글 수정 (성지순례)
- 댓글 수정 (자유게시판)
이미지 관련
- 이미지 파일 리사이징은 성공했는데, 파일 사이즈가 작아진다고 해서 이미지 전송속도의 향상은 없었음. 더 시도해봐야 할 것 같다.

[FEAT #49] 댓글(자유게시판&성지순례) 수정&삭제

---

src/main/java/com/favoriteplace/app/controller/GuestBookController.java
src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
src/main/java/com/favoriteplace/app/domain/community/HashTag.java
src/main/java/com/favoriteplace/app/dto/community/GuestBookRequestDto.java
src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
src/main/java/com/favoriteplace/app/service/GuestBookCommandService.java
src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java

- 성지순례 인증글 작성 api 개발
- /posts/guestbooks/{} 엔드포인트 겹침 문제 해결
- 이미지 업로드 성공 확인 (유저 null 이미지로 인해 전체 정보 조회는 확인하지 못함)

[FEAT] 성지순례 인증글 작성 api 개발

---

.gitignore
scripts/start.sh
src/main/java/com/favoriteplace/FavoritePlaceApplication.java
src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/ShopController.java
src/main/java/com/favoriteplace/app/domain/enums/ItemCategory.java
src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
src/main/java/com/favoriteplace/app/repository/ItemRepository.java
src/main/java/com/favoriteplace/app/service/MemberService.java
src/main/java/com/favoriteplace/app/service/ShopService.java
src/main/java/com/favoriteplace/global/gcpImage/ConvertUuidToUrl.java
src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
src/main/java/com/favoriteplace/global/util/SchedulerService.java

`추가 수정사항`
- 스케줄링 기능과 벌크성 수정 연산을  통해 일주일 지난 NEW 카테고리 상품들은 NORMAL로 이동하도록
-  상점 - 신상품 목록 조회시 모든 상품은 7일동안 보여질 수 있도록 수정
- 이미지 관련하여 application.yml 수정 및 ConvertUuidToUrl의 주소 변경

[FEAT #54] 상품 구매 API 구현

---

src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
src/main/java/com/favoriteplace/app/converter/RallyConverter.java
src/main/java/com/favoriteplace/app/dto/travel/RallyDto.java
src/main/java/com/favoriteplace/app/repository/AddressRepository.java
src/main/java/com/favoriteplace/app/repository/RallyRepository.java
src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java

- 애니메이션 이름 별 검색 (랠리검색) api 개발
- 지역 별 검색 (성지순례검색) api 개발

[FEAT #62] 성지순례 검색 api 구현(like 사용)

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/controller/GuestBookController.java
src/main/java/com/favoriteplace/app/controller/PostController.java
src/main/java/com/favoriteplace/app/converter/CommentConverter.java
src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
src/main/java/com/favoriteplace/app/domain/community/Post.java
src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java
src/main/java/com/favoriteplace/app/repository/Empty.java
src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
src/main/java/com/favoriteplace/app/repository/PostRepository.java
src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
src/main/java/com/favoriteplace/app/service/community/PostQueryService.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByContent.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByNickname.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByTitle.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByContent.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByNickname.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByTitle.java
src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchStrategy.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/exception/ExceptionHandlerAdvice.java
src/main/java/com/favoriteplace/global/gcpImage/UploadImage.java

- 커뮤니티 - 자유게시판 : 검색 by.제목, 닉네임, 내용
- 커뮤니티 - 성지순례 인증글 : 검색 by.제목, 닉네임, 내용
- 이미지 병렬 처리

[FEAT #61] 커뮤니티(자유게시판&성지순례인증글) 검색 api 구현, 이미지 병렬 처리

---

src/main/java/com/favoriteplace/app/controller/MyPageController.java
src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
src/main/java/com/favoriteplace/app/domain/Member.java
src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
src/main/java/com/favoriteplace/app/service/MemberService.java
src/main/java/com/favoriteplace/app/service/MyPageCommandService.java
src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java
src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java

- 성지순례 지역 상세 api 수정
- 마이페이지, 상점 아이템 착용 api 개발
- 성지순례 인증글 이미지 확인 로직 추가

[FIX] 성지순례 api 수정 및 아이템 착용 api 개발

---

src/main/java/com/favoriteplace/global/util/DateTimeFormatUtils.java

"yyyy.MM.dd HH.mm"의 형식을 "yyyy.MM.dd"의 형식으로 수정했습니다.

[FIX #80] 날짜 출력 형식 수정

---

src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
src/main/java/com/favoriteplace/app/service/community/PostCommandService.java

[FEAT #80] 이미지 null 처리

---

src/main/java/com/favoriteplace/InitDB.java
src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java

[FIX #91] 성지순례 인증하기 api 수정

---

src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java

[FIX #80] 성지순례 인증글 상세 정보 response 수정

---

build.gradle
src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
src/main/java/com/favoriteplace/app/controller/PostCommentController.java
src/main/java/com/favoriteplace/app/domain/community/Comment.java
src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
src/main/java/com/favoriteplace/app/domain/community/Post.java
src/main/java/com/favoriteplace/app/domain/enums/CommentType.java
src/main/java/com/favoriteplace/app/dto/community/CommentRequestDto.java
src/main/java/com/favoriteplace/app/repository/CommentRepository.java
src/main/java/com/favoriteplace/app/service/community/CommentCommandService.java
src/main/java/com/favoriteplace/global/config/SwaggerConfig.java
src/main/java/com/favoriteplace/global/exception/ErrorCode.java

[REFACTOR #109] 자유게시판&성지순례 인증글 댓글 등록, 삭제 리펙토링

---

src/main/java/com/favoriteplace/app/controller/HealthCheckController.java

[DEPLOY #124] healthcheck controller 수정

---

src/main/java/com/favoriteplace/app/controller/HealthCheckController.java

[DEPLOY #124] healthCheckController 수정

[DEPLOY #124] healthCheckController 수정

---

src/main/java/com/favoriteplace/app/controller/HealthCheckController.java

[DEPLOY] main <- develop 병합

---

src/main/java/com/favoriteplace/app/controller/MemberController.java
src/main/java/com/favoriteplace/app/domain/Member.java
src/main/java/com/favoriteplace/app/dto/member/KaKaoSignUpRequestDto.java
src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
src/main/java/com/favoriteplace/app/service/MemberService.java
src/main/java/com/favoriteplace/global/security/config/FeignClientConfig.java

- 카카오 회원가입 구현
- closed #121 
- postman 화면
곧곧 채울게요...files changed 위주로 먼저 코리 달아주셔도 됩니다!!
문제를 해결하면서 도움이 되었거나, 참고했던 사이트(코드링크)

[FEAT] 카카오 회원가입 구현

---

.github/workflows/develop.yml
.github/workflows/main.yml
src/main/java/com/favoriteplace/app/dto/member/AuthKakaoLoginDto.java

- 카카오 회원가입 AuthKakaoLoginDto json 매핑 못하는 문제 해결 반영 및 배포를 위한 병합

[FIX #121] 카카오 회원가입 AuthKakaoLoginDto json 매핑 못하는 문제 해결

---

src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
src/main/java/com/favoriteplace/global/websocket/RedisService.java

- STOMP connect 이벤트가 안 보내지는 문제를 해결했습니다
- 캐시의 동기화 문제를 개선했습니다
- closed #138
이전에 발생한 버그가 redis 문제가 아니라 리팩토링 과정에서 코드 병합이 잘못돼서 생긴 문제였습니다. 해결 후 pr 올렸습니다!
https://kadosholy.tistory.com/123

[FIX #138] STOMP connect 이벤트 버그 해결

---

src/main/java/com/favoriteplace/global/websocket/WebSocketConfig.java

- SockJS 설정을 제거했습니다.
- closed #145
(생략)

[FIX #145] SockJS 설정 제거

---

build.gradle

[CHORE] build.gradle 잘못된 코드 삽입 삭제

[CHORE] build.gradle 잘못된 코드 삽입 삭제

---

.github/workflows/main.yml

[CHORE] main.yml 수정
